version: '3.8'

networks:
  app_network:
    driver: bridge
  db_network:
    driver: bridge

services:
  # -----------------------------
  # PostgreSQL
  # -----------------------------
  psql:
    image: postgres:16
    container_name: devops_db_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5438:5432"
    networks:
      - db_network
      - app_network

  # -----------------------------
  # PgAdmin
  # -----------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - psql
    networks:
      - db_network

  # -----------------------------
  # Gateway
  # -----------------------------
    gateway:
      build:
        context: ./gateway
        dockerfile: Dockerfile
    container_name: devops_gateway_container
    restart: always
    volumes:
      - ./gateway/app:/app
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      AUTH_SERVICE_URL: http://auth-service:8000
      TEST_SERVICE_URL: http://test-service:8000
      SESSION_SERVICE_URL: http://session-service:8000
    networks:
      - app_network
      - db_network
    depends_on:
      - psql
      - auth-service
      - test-service
      - session-service

  # -----------------------------
  # Auth Service
  # -----------------------------
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: devops_auth_service_container
    restart: always
    volumes:
      - ./auth-service/app:/app
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
    networks:
      - app_network
      - db_network
    depends_on:
      - psql

  # -----------------------------
  # Test Service
  # -----------------------------
  test-service:
    build:
      context: ./test-service
      dockerfile: Dockerfile
    container_name: devops_test_service_container
    restart: always
    volumes:
      - ./test-service/app:/app
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      SESSION_SERVICE_URL: http://session-service:8000
      AUTH_SERVICE_URL: http://auth-service:8000
    networks:
      - app_network
      - db_network
    depends_on:
      - psql

  # -----------------------------
  # Session Service
  # -----------------------------
  session-service:
    build:
      context: ./session-service
      dockerfile: Dockerfile
    container_name: devops_session_service_container
    restart: always
    volumes:
      - ./session-service/app:/app
    ports:
      - "8004:8000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8000
      TEST_SERVICE_URL: http://test-service:8000
    networks:
      - app_network
      - db_network
    depends_on:
      - psql

  # -----------------------------
  # Nginx Reverse Proxy
  # -----------------------------
  nginx:
    image: nginx:stable-alpine
    container_name: devops_nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway
    networks:
      - app_network

volumes:
  db_data:
  pgadmin_data:
